export { default as Main } from './Main';
export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Logout } from './Logout';
export { default as Profile } from './Profile';
export { default as Leaderboard } from './Leaderboard';
// export { default as Forum } from './Forum';
export { default as Forum } from './ForumUpdated';
export { default as NotFound } from './NotFound';
export { default as GameScreen } from './GameScreen';
